Mongo:
  URI: "mongodb+srv://127.0.0.1"

jedis:
  host: "redis-19823.c258.us-east-1-4.ec2.cloud.redislabs.com"
  port: 19823
  user: "FrozenHCF"
  pass: "yQ4evkvAStkc3eXTjDX4rFeMKFTr2zZg"

serverName: FoxHCF
networkWebsite: foxhcf.net
statsRoot: foxhcf.net/teams
tab:
  serverName: '&6&lHCTeams'
  sectionColor: '&5'
  infoColor: '&e'
scoreboard:
  title: "&e&lHCTeams &c[Map 1]" # doesmt worjk
nightmare:
  enabled: true
  worldName: "NightmareEvent"
glowstoneMountain: false
cavern: false
startingTimer: false
forceInvites: true
squads: false
idleCheck: true
uhcHealing: false
passiveTag: true
allowBoosting: false
waterPlacementInClaims: false
blockRemoval: false
rodPrevention: false
skybridgePrevention: false
reduceArmorDamage: true
blockEntitiesThroughPortals: true
archerTagColor: YELLOW
defaultRelationColor: RED
legions: true
pvpClasses:
  archer: true
  bard: true
  rogue: true
  ranger: true
minerWorld:
  regen:
    COAL_ORE: 30
    IRON_ORE: 60
    GOLD_ORE: 90
    DIAMOND_ORE: 120
potions:
  REGEN:
    splash: false
    drinkables: false
  SPEED:
    splash: true
    drinkables: true
  FIRE_RESISTANCE:
    splash: true
    drinkables: true
  POISON:
    splash: true
    drinkables: false
  INSTANT_HEAL:
    splash: true
    drinkables: true
  NIGHT_VISION:
    splash: true
    drinkables: true
  WEAKNESS:
    splash: false
    drinkables: false
  STRENGTH:
    splash: false
    drinkables: false
  SLOWNESS:
    splash: true
    drinkables: false
  INSTANT_DAMAGE:
    splash: false
    drinkables: false
  WATER_BREATHING:
    splash: true
    drinkables: true
  INVISIBILITY:
    splash: false
    drinkables: false

    #redis shit 100% not stolen from qlib :D

reclaim:
  Owner:
    - "bc lol"
  Fox:
    - "bc lol"
  Legend:
    - "bc lol"
  Pro:
    - "bc lol"
  MVP:
    - "bc lol"
  VIP:
    - "bc lol"
  Default:
    - "bc lol"

redeem:
  Embry_:
    - "bc lol"
  Nopox:
    - "bc lol"

deathban-arena:
  world: "world"
  x: 0
  y: 256
  z: 0
  yaw: 0
  pitch: 0

title:
  animation:
    - text: "&e&lPvPBeach"
      delay: 240
    - text: "&e&lP&e&lV&f&lP&e&lBeach"
      delay: 240
    - text: "&e&lPV&e&lP&f&lB&e&leach"
      delay: 240
    - text: "&e&lPVP&e&lB&f&le&e&lach"
      delay: 240
    - text: "&e&lPVPB&e&le&f&la&e&lch"
      delay: 240
    - text: "&e&lPVPBe&e&la&f&lc&e&lh"
      delay: 240
    - text: "&e&lPVPBea&e&lc&f&lh"
      delay: 240
    - text: "&e&lPVPBeac&e&lh"
      delay: 240
    - text: "&e&lPVPBeach"
      delay: 360
    - text: "&f&lPvPBeach"
      delay: 360
    - text: "&6&lPvPBeach"
      delay: 360
    - text: "&f&lPvPBeach"
      delay: 360
    - text: "&e&lPvPBeach"
      delay: 360
    - text: "&f&lPvPBeach"
      delay: 360

  #IGNORE THIS STUFF, I'M TESTING
  Redis:
    Host: 'redis-15371.c99.us-east-1-4.ec2.cloud.redislabs.com'
    Password: 'k5SYX0bEmU1PFthdCrn08fR8u5WinVHw'
    Port: 15371
    DbId: 7
  BackboneRedis:
    Host: 'redis-15371.c99.us-east-1-4.ec2.cloud.redislabs.com'
    Password: 'k5SYX0bEmU1PFthdCrn08fR8u5WinVHw'
    Port: 15371
    DbId: 7
  UUIDCache:
    Backend: 'net.frozenorb.foxtrot.uuid.impl.RedisUUIDCache'